# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/translator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/translator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/translator.proto\x12\ntranslator\"J\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0bsource_lang\x18\x02 \x01(\t\x12\x13\n\x0btarget_lang\x18\x03 \x01(\t\",\n\x11TranslateResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t\"P\n\x15\x42\x61tchTranslateRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x13\n\x0bsource_lang\x18\x02 \x01(\t\x12\x13\n\x0btarget_lang\x18\x03 \x01(\t\"2\n\x16\x42\x61tchTranslateResponse\x12\x18\n\x10translated_texts\x18\x01 \x03(\t2\xb3\x01\n\nTranslator\x12J\n\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x1d.translator.TranslateResponse\"\x00\x12Y\n\x0e\x42\x61tchTranslate\x12!.translator.BatchTranslateRequest\x1a\".translator.BatchTranslateResponse\"\x00\x42\x12Z\x10translator/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.translator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020translator/proto'
  _globals['_TRANSLATEREQUEST']._serialized_start=38
  _globals['_TRANSLATEREQUEST']._serialized_end=112
  _globals['_TRANSLATERESPONSE']._serialized_start=114
  _globals['_TRANSLATERESPONSE']._serialized_end=158
  _globals['_BATCHTRANSLATEREQUEST']._serialized_start=160
  _globals['_BATCHTRANSLATEREQUEST']._serialized_end=240
  _globals['_BATCHTRANSLATERESPONSE']._serialized_start=242
  _globals['_BATCHTRANSLATERESPONSE']._serialized_end=292
  _globals['_TRANSLATOR']._serialized_start=295
  _globals['_TRANSLATOR']._serialized_end=474
# @@protoc_insertion_point(module_scope)
