// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/translator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SourceLang    string                 `protobuf:"bytes,2,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`
	TargetLang    string                 `protobuf:"bytes,3,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translator_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *TranslateRequest) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

type TranslateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslatedText string                 `protobuf:"bytes,1,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

type BatchTranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	SourceLang    string                 `protobuf:"bytes,2,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`
	TargetLang    string                 `protobuf:"bytes,3,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTranslateRequest) Reset() {
	*x = BatchTranslateRequest{}
	mi := &file_proto_translator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTranslateRequest) ProtoMessage() {}

func (x *BatchTranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTranslateRequest.ProtoReflect.Descriptor instead.
func (*BatchTranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translator_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTranslateRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchTranslateRequest) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *BatchTranslateRequest) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

type BatchTranslateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TranslatedTexts []string               `protobuf:"bytes,1,rep,name=translated_texts,json=translatedTexts,proto3" json:"translated_texts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchTranslateResponse) Reset() {
	*x = BatchTranslateResponse{}
	mi := &file_proto_translator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTranslateResponse) ProtoMessage() {}

func (x *BatchTranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTranslateResponse.ProtoReflect.Descriptor instead.
func (*BatchTranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTranslateResponse) GetTranslatedTexts() []string {
	if x != nil {
		return x.TranslatedTexts
	}
	return nil
}

var File_proto_translator_proto protoreflect.FileDescriptor

const file_proto_translator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/translator.proto\x12\n" +
	"translator\"h\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vsource_lang\x18\x02 \x01(\tR\n" +
	"sourceLang\x12\x1f\n" +
	"\vtarget_lang\x18\x03 \x01(\tR\n" +
	"targetLang\"<\n" +
	"\x11TranslateResponse\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\"o\n" +
	"\x15BatchTranslateRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1f\n" +
	"\vsource_lang\x18\x02 \x01(\tR\n" +
	"sourceLang\x12\x1f\n" +
	"\vtarget_lang\x18\x03 \x01(\tR\n" +
	"targetLang\"C\n" +
	"\x16BatchTranslateResponse\x12)\n" +
	"\x10translated_texts\x18\x01 \x03(\tR\x0ftranslatedTexts2\xb3\x01\n" +
	"\n" +
	"Translator\x12J\n" +
	"\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x1d.translator.TranslateResponse\"\x00\x12Y\n" +
	"\x0eBatchTranslate\x12!.translator.BatchTranslateRequest\x1a\".translator.BatchTranslateResponse\"\x00B\x12Z\x10translator/protob\x06proto3"

var (
	file_proto_translator_proto_rawDescOnce sync.Once
	file_proto_translator_proto_rawDescData []byte
)

func file_proto_translator_proto_rawDescGZIP() []byte {
	file_proto_translator_proto_rawDescOnce.Do(func() {
		file_proto_translator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_translator_proto_rawDesc), len(file_proto_translator_proto_rawDesc)))
	})
	return file_proto_translator_proto_rawDescData
}

var file_proto_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_translator_proto_goTypes = []any{
	(*TranslateRequest)(nil),       // 0: translator.TranslateRequest
	(*TranslateResponse)(nil),      // 1: translator.TranslateResponse
	(*BatchTranslateRequest)(nil),  // 2: translator.BatchTranslateRequest
	(*BatchTranslateResponse)(nil), // 3: translator.BatchTranslateResponse
}
var file_proto_translator_proto_depIdxs = []int32{
	0, // 0: translator.Translator.Translate:input_type -> translator.TranslateRequest
	2, // 1: translator.Translator.BatchTranslate:input_type -> translator.BatchTranslateRequest
	1, // 2: translator.Translator.Translate:output_type -> translator.TranslateResponse
	3, // 3: translator.Translator.BatchTranslate:output_type -> translator.BatchTranslateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_translator_proto_init() }
func file_proto_translator_proto_init() {
	if File_proto_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_translator_proto_rawDesc), len(file_proto_translator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translator_proto_goTypes,
		DependencyIndexes: file_proto_translator_proto_depIdxs,
		MessageInfos:      file_proto_translator_proto_msgTypes,
	}.Build()
	File_proto_translator_proto = out.File
	file_proto_translator_proto_goTypes = nil
	file_proto_translator_proto_depIdxs = nil
}
